### ISSUE TITLE
Add a check box on main display to disable status info from wsjtx and info from hamlib

### ISSUE THREAD

**Issue by barjac** [ea4k/klog#11]
When wsjtx is running it impossible to edit a record or manually enter a record without it being overwritten or deleted by data coming from wsjtx.
It is inconvenient to stop wsjtx and impossible to use klog settings to turn off status info, as doing so clears the edit in progress.

**Comment by ea5wa** [comment]
Doesn't it solved unchecking the third checkbox in Setup-WSJTX? Update status from WSJT

**Comment by barjac** [comment]
On 15/02/2021 17:50, ea5wa wrote:
> Doesn't it solved unchecking the third checkbox in Setup-WSJTX? Update 
> status from WSJT
> 
> 

No, because this is needed instantly.

Entering 'Setup' for any reason wipes any data already entered.

**Comment by barjac** [comment]
To clarify this issue further explanation of the use case that causes problems is needed:
A station is using a wsjtx mode on HF and has qrz.com lookup and hamlib running.
The current callsign in wsjtx is controlling the 'callsign' field in klog.
Hamlib (read only) is setting the Mode, Band and frequency.
Now a DX CQ call is heard on a different radio, maybe VHF, and is worked.
In order to log this call, wsjtx, and hamlib would have to be disabled in setup.
As you can imagine this is impractical.

I now realize that qrz.com is not an issue once wsjtx stops overwriting the callsign, but hamlib is.

**Comment by barjac** [comment]
Can this be increased in priority please?
I just replied to a call on 4m while I was doing some testing on 17m FT8. The 4M radio is in no way connected to klog/wsjtx or hamlib. I simply wanted to quickly, manually log a contact.
Impossible!
I had to turn off the HF radio, close wsjtx, CLEAR the QSO data, which does not clear the band/ frequency/mode and then start entering the QSO. QRZ.com did fill the name, qth and locator.
This is really needed!

**Comment by ea4k** [comment]
Solved in master
