### ISSUE TITLE
Editing removes QTH and name

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#113]
When editing a QSO the QTH and name are not displayed and therefore lost.

**Comment by barjac** [comment]
It only fails on the first attempt to edit. Double clicking twice on the record does show name and qth. So unless you know that, data could be lost if the record is then saved (modify). Also there may be other fields affected, I have not had chance to check all tabs.

**Comment by ea4k** [comment]
I can't reproduce the error. Is it still there?
Can you please send me detailed instructions to reproduce it?

Thanks

**Comment by barjac** [comment]
This was fixed in 1.5.1 :)
