### ISSUE TITLE
Hamlib: On program start, the mode, band and frequency are not picked up by KLog

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#126]
On program start, the mode, band and frequency are still not picked up by Hamlib and entered. Only when a change is made at the rig does the data get transferred. It's as though the polling does not start. Moving the VFO by a few Hz is needed to get the info into klog.

**Comment by barjac** [comment]
Testing further with this in 1.5.2, if the program is started and a call is entered into the callsign field the qrz.com lookup does not happen either.
However if setup -> setup -> OK is used then hamlib enters  rig band, mode, frequency and qrz.com lookup takes place correctly.
Notice that using setup annoyingly clears the previously entered callsign.
This is all demonstrated in the attached video.

https://user-images.githubusercontent.com/1324702/118380956-010e1780-b5de-11eb-8731-877d289d8481.mp4
