### ISSUE TITLE
"RX Frequency" displayed in red after importing QSOs using ADIF with or without this data

### ISSUE THREAD

**Issue by ea5wa** [ea4k/klog#15]
After importing QSOs in ADIF without "Rx Frequency" field, RX Frequency in QSO Tab is displayed in red with a value = 0,000.

**Comment by ea4k** [comment]
It is in red because 0.000 is not a valid frequency for KLog but as you say,  the problem is that RX freq is not being imported.

**Comment by ea5wa** [comment]
It's already fixed with the last filemanager.cpp modifications
