### ISSUE TITLE
Unexpected Setup dialog behavior

### ISSUE THREAD

**Issue by foldynl** [ea4k/klog#178]
I go to a main menu->Setup->Setup and change my Locator from JN70GD to JO70GA (or callsign from xxxx to yyyy) and press Cancel. 
Then I go to menu->Setup->Setup again to verify the result of operation. Even though I pressed Cancel, I can see modified values (JO70GA - expecting JO70GD). But if KLog is restarted then I can see the old values in the Setup dialog.

An expecting behavior is that the new values are saved only when they are confirmed by OK button.

**Comment by ea4k** [comment]
slotReadConfigData is where the data is read. Should we call it everytime it is shown?
