### ISSUE TITLE
UDP server does not start on KLog start

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#198]
WSJTX are not received on KLog when started (properly configured in settings) until not configured again in the setup.

**Comment by barjac** [comment]
This is similar to #126 which refers to hamlib and qrz.com.
Maybe all external communication fails to be initialized on startup until Setup->Setup->OK is clicked?

**Comment by ea4k** [comment]
It should be solved know.
Hamlib and UDP server are started once the KLog main window is shown.
