### ISSUE TITLE
Calls coming from WSJTX are not showing the right DXCC once one is logged.

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#24]

**Comment by ea5wa** [comment]
When logging a QSO from WSJT-X, Country is not correctly shown in the Info widget. Correct Country appears briefly (a second or less) and then replaced by a wrong one (coming from the first logged QSO after KLog started or after clicking OK on Setup Dialog). Is just after the message "QSO logged from WSJT-X" (Info widget)  when KLog fails to show the Country correctly.

Adding the qso with the Add button on mainqsoentrywidget is working correctly

**Comment by ea5wa** [comment]
Removing the timer (timerInfoBars) on MainWindow::slotWSJTXloggedQSO is working correctly
