### ISSUE TITLE
[Enhancement] - Using the same graphic elements for the same things 

### ISSUE THREAD

**Issue by foldynl** [ea4k/klog#266]
The radio button is used in several places in the same situation as the check button elsewhere. 

For example:
The main window -> Comment -> "Keep this data" is radio button but the main window -> Others -> "Keep propagation mode" is a check button. The same situation is the main window -> My Data -> "keep this data" is a radio button but the main window -> Satellite -> "Keep this data" is a check box.

The similar situation occurs in Setup dialog. The DX-Cluster uses radio buttons but Misc uses check buttons. I think that DX-Cluster should use a check buttons.

**Comment by ea4k** [comment]
Good comment.
I think all of them can be QCheckBox. I will try to go that way.
