### ISSUE TITLE
[Enhancement] - Improve QSO time

### ISSUE THREAD

**Issue by foldynl** [ea4k/klog#268]
The main window -> Date&Time fields are followed by check button, unfortunately, there is no description what exactly the check button does.

![time_klog](https://user-images.githubusercontent.com/942769/121336159-8a81e280-c91b-11eb-83e8-11e11fa7db25.png)

The label may not be used when, for example, following buttons will be used:
![play](https://user-images.githubusercontent.com/942769/121336765-20b60880-c91c-11eb-9298-3bbd193b87cd.png)
![stop](https://user-images.githubusercontent.com/942769/121336788-23186280-c91c-11eb-8b4c-dd336f365ac8.png)

**Comment by ea4k** [comment]
I have added a label.
I am not really sure if it is redundant or not.

![imagen](https://user-images.githubusercontent.com/29511627/121392308-8c659900-c94f-11eb-92c2-ae6cbf8de1fa.png)

What do you think?

**Comment by ea4k** [comment]
Added

**Comment by foldynl** [comment]
Thanks..much better. 
To be hones, I would prefer to use an icons - it does not burden translators who have to constantly update their translations. Otherwise, I am thinking about the meaning of "real time". I know what you want to say but "real time" has another meaning in IT terminology  (https://en.wikipedia.org/wiki/Real-time). For example, in case of "Send each QSO to ClubLog in real time" it would be better to use "Send each QSO to ClubLog immediately". Unfortunately, I am not sure what should be used in case of "real time" beside date&time. Therefore, the button + icon is better solution. I will try to look at the source as it is implemented there.
