### ISSUE TITLE
[Enhancement] - Move Setup menu to File menu

### ISSUE THREAD

**Issue by foldynl** [ea4k/klog#269]
please consider moving the Setup->Setup menu to a File as Preferences (or Settings). This will reduce the space on the main menu panel.

**Comment by ea5wa** [comment]
Setup, Settings, Options..... What will be the best descriptor?

**Comment by foldynl** [comment]
I guess that the Settings. "Setup" is rather one-time event. When you start the application for the first time, you do "Setup". "Settings" or "Options" are on the same level.

**Comment by ea4k** [comment]
Let's use Settings, please.
