### ISSUE TITLE
HAMLIB parameters are not saved correctly in KLog v1.6

### ISSUE THREAD

**Issue by foldynl** [ea4k/klog#293]
A new version 1.6 does not save a RIG type, Baud and other parameters to the config file. It seems that there are missing many parameter in SetupPageHamLib::getData. It seems that commit 80a999182cc6ac57bc7e3af30dbaf36ce9b4f186 broke it.

**Comment by ea4k** [comment]
Thank you!

**Comment by foldynl** [comment]
Unfortunately, it is still not working correctly. The RigType is always 0. The easy test is to go to setup menu, select rig a press OK. Then go to setup menu again and you can see always radio named "2050"

**Comment by foldynl** [comment]
To be honest, the data for hamlib are prepared by SetupPageHamLib::getData. I can see that this line

```
QString _rigType, _serialPort, _baudsSpeed;//, dataBits, stopBits, handshake, flowControlLine;

_output = _output + "HamLibRigType=" + QString::number(hamlib->getModelIdFromName(_rigType)) + ";\n";
```

but there is no assignment for _rigType. The same situation is for HamlibSerialBauds etc.

There are missing following lines which were removed by commit 80a999182cc6ac57bc7e3af30dbaf36ce9b4f186
```
_rigType = rigTypeComboBox->currentText();
_serialPort = serialPortComboBox->currentText();
 _baudsSpeed = serialBaudsComboBox->currentText();
```
