### ISSUE TITLE
Log info on top is wrong on log change

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#347]
the log notification at the top of the main window now showing the wrong log after changing logs

**Comment by ea4k** [comment]
Bug Major - No log is ever highlighted as current in Settings -> Logs and even selecting one and OK-ing does not then show it as selected on next entering the dialogue. More importantly when changing the log by selecting a different one and OK-ing, the message in the main window header does not change. The log DOES change in the log list but there is no indication anywhere that this has happened.

**Comment by barjac** [comment]
This appears to be partly fixed in 1.8.4 - the main window header is now updated instantly. The appropriate line in the Settings->Logs dialogue is still not highlighted unless unless clicked.
