### ISSUE TITLE
QRZcomAuto= in klogrc is removed if checkbox unchecked.

### ISSUE THREAD

**Issue by barjac** [ea4k/klog#35]
If "Tools->QRZ.com tools->Check always the current callsign in QRZ.com" is unchecked, OR "Setup->eLOG->QRZ->Check Automatically" is unchecked, the next time "Setup->OK is used, the entry: "QRZcomAuto=True;" is removed from klogrc
It should only be set False not removed. This is 1.4.6.

**Comment by ea4k** [comment]
Closed in 1.5
