### ISSUE TITLE
"QSOs to be sent to LoTW" shows already sent QSOs

### ISSUE THREAD

**Issue by ea5wa** [ea4k/klog#354]
"QSOs to be sent to LoTW" shows already sent QSOs. These QSOs are correctly saved and eQSL tab shows that are already uploaded to LoTW, but even that, selecting "Tools-Send queued QSOs to LoTW" and selecting the callsign, the window shows already uploaded QSOs.
Maybe the query is failing

**Comment by ea4k** [comment]
To reproduce: 
- Add one QSO to the log, ensure lots qsl is queued to be sent.
- Send  and upload QSO to LoTW.
- Check that QSO has the LoTW marked as sent.
- Select send the queued QSOs,  the just previously sent QSOs ... it is shown as as sent but QSOs are still appearing to be sent.
