### ISSUE TITLE
KLog does not connect to USB/serial radios in Ubuntu. 

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#355]
![Screenshot at 2021-08-28 07-23-28.png](https://user-images.githubusercontent.com/29511627/131221877-2a09bab6-4650-49fa-a6ff-c24f534f5cd7.png)

**Comment by ea5wa** [comment]
I've just check it yesterday and was working fine in Ubuntu.
My problem was in windows

**Comment by ea5wa** [comment]
I'm checking it with Windows 10 and no success. Hamlib seems connected "Test is OK" but no changes in frequency. Same configuration in Ubuntu is working perfectly.
You should change the title....
