### ISSUE TITLE
Clublog: Log upload fails with error 201.

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#359]
![IMG_20210829_223934_183.jpg](https://user-images.githubusercontent.com/29511627/131264689-40697fff-7d27-4c2b-8bb7-97fb5f3dc050.jpg)

**Comment by ea5wa** [comment]
After making a new QSO, I tried to upload this new QSO to Clublog with the option in "Tools-Upload QSOs to Clublog" and again error 201 message

**Comment by ea4k** [comment]
Can you please check it again?
Please tell me current version and operating system.

It is working in my KLog.

**Comment by ea5wa** [comment]
Testing it with your master (1.8.5) works fine. Testing it again with 1.8.4 (windows 11) I have still same error message

**Comment by ea5wa** [comment]
Tested in two different windows laptops (one with w10 and the other with w11) with 1.8.4 version, same error message

**Comment by ea4k** [comment]
Not able to reproduce the error in KLog 1.8.5

**Comment by ea4k** [comment]
I close as I can't reproduce
