### ISSUE TITLE
Modifying a record incorrectly sets some properties for next

### ISSUE THREAD

**Issue by conorpeterson** [ea4k/klog#377]
Issue:
When the user modifies an existing record, after the user clicks "modify" to commit their changes, the next record will have the "Split" checkbox set, and the Satellite dropdown will be set to "Other - Sat not in the list."

Expected behavior:
After clicking "modify" the record fields should be cleared exactly as if you had clicked "clear."

Additional note:
If the user goes on to fill out a new record but fails to correct the satellite property, TQSL will refuse to upload the record because it does not recognize the satellite.

Version:
I am using KLog 1.8.5 on Windows 10.

**Comment by ea5wa** [comment]
Should be fixed in the next release 1.8.7
