### ISSUE TITLE
Frequency fields only allow single-digit edits

### ISSUE THREAD

**Issue by conorpeterson** [ea4k/klog#378]
Issue:
When modifying a frequency with a decimal point ('.'): if the user selects the decimal portion and types a new number, only the first numeral they typed is recognized.

Example: frequency field populated with "7.187". User wishes to change it to "7.254".
1. User double-clicks to select "187"
2. User types '2' '5' '4'
3. Only the '2' was recognized. The field now reads "7.200" and the selection is cleared.

Expected behavior:
In Libreoffice Calc, Excel, Notepad, and most other text editing programs, the full selection ("187") is replaced by the first character typed ('2'), with subsequently typed characters then appended to the string.

The current workaround is to select and replace individual digits, which slows down the process of manually entering contacts.

Version:
I'm using KLog 1.8.5 on Windows 10.

**Comment by conorpeterson** [comment]
Can confirm it is still an issue in 2.3

**Comment by boryszef** [comment]
I can confirm the issue and it is super annoying in otherwise great piece of software that is KLog. The problem is because valueChanged is emitted after every character is typed. Setting keyboardTracking to false should fix the problem, as this will trigger the decimal fill only when the focus is lost or the buttons are used. I made a pull request with this simple fix.

**Comment by ikbenkous** [comment]
I think the desired behavior should be to clear the kHz from the input field:

1. User presses once inside spinbox. On 20 meters, the input box would now contain "14." with the text cursor after it.
2. The user then types in '2', '1' and '6'.
3. The user can then change confirm by pressing return, enter or tab to switch to the next field.

This should be doable with a bit of event hackery, but I'm no Qt expert so take this opinion with salt.

**Comment by ikbenkous** [comment]
~~Does #617 fix this?~~
Yes it does.
