### ISSUE TITLE
User configurable input fields

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#4]
Add one configurable field in the My Data and another one in Other.
To allow the user to manage SOTA, contests...

Add 2-3 qcombobox for the user ro select the ADIF field and 2-3 qlineedit for the data.

**Comment by garethhowell** [comment]
The initial enhancement implieed there was to be an enhancement to My Data ( presumably to add My_SOTA_REF).
I can't see this change.
I would really like to be able to use klog for SOTA activations, so having MY_SOTA_REF would be very useful.
