### ISSUE TITLE
KLog is not updating the hamlib data

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#407]
Freq is received from the radio but not updated.
Check signals(hamlib freqChanged)/slot (mainwindow), something is failing there

**Comment by barjac** [comment]
For me there is no communication at all unless wsjtx is running (read only) using rigctld.

**Comment by w5pny** [comment]
For me Klog 1.8.6 does not communicate with radio at all, but the settings->hamlib tests work.

**Comment by ea4k** [comment]
The problem is between the hamlib and the mainwindow classes communication.

The hamlib class is correctly polling and getting the freq and mode from the radio but it is not properly emitting the signals or (more probably) the mainwindow class is not receiving the signal.
