### ISSUE TITLE
Add ability to block callsigns from the map when the locator is known to be incorrect.

### ISSUE THREAD

**Issue by barjac** [ea4k/klog#435]
This happens often when stations do not enter their locator correctly in QRZ.com and where this is the only source available.

**Comment by ea4k** [comment]
If the locator is known to be bad... the user should simply remove that locator, no?
Can you please describe your request with more details?

**Comment by barjac** [comment]
Yes you are correct, I was forgetting that we can now remove data entered by qrz.com manually without it being automatically replaced.
