### ISSUE TITLE
Debian repo update

### ISSUE THREAD

**Issue by TuxedoHam** [ea4k/klog#438]
Wondering when there is going to be an update for the Debian repo as we still on version 1.8.6 with broken hamlib

**Comment by ea4k** [comment]
KLog 2.0 has just been uploaded to the unstable Debian repository.
Data should be updated soon here:
https://tracker.debian.org/pkg/klog
https://buildd.debian.org/status/package.php?p=klog

(Thank you for the reminder)

**Comment by TuxedoHam** [comment]
Thanks for that I have updated to 2.0-1
