### ISSUE TITLE
QSOs coming from WSJT-X are not sent to Queue for eQSL

### ISSUE THREAD

**Issue by ea5wa** [ea4k/klog#45]
QSOs manually entered are Queued to be sent to eQSL, but not new QSOs coming from WSJT-x.

**Comment by ea4k** [comment]
Closed in 1.4.7

**Comment by ea5wa** [comment]
Is not working correctly. Parameter sendQSLByDefault missing on calling  addQSOFromWSJTX function inside mainwindow.cpp
