### ISSUE TITLE
Fed. Rep. of Germany missing from DXCC list

### ISSUE THREAD

**Issue by n6paz** [ea4k/klog#460]
The "Fed. Rep. of Germany" appears to be missing in the "DXCC" tab.   See attached image. 

![Screenshot 2022-05-31 161304](https://user-images.githubusercontent.com/92184426/171298861-9ac4d748-7b1e-4511-bc59-d9d88a028366.png)

**Comment by n6paz** [comment]
​Thank you for your support.

73's de Oscar, N6PAZ

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

------- Original Message -------

**Comment by ea4k** [comment]
What KLog versión are you using?

**Comment by n6paz** [comment]
Today I am using version 2.2.1. When the problem was reported it was version 2.0.

The problem described has been fixed in 2.2.1

73's de Oscar, N6PAZ

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

------- Original Message -------
