### ISSUE TITLE
Klog CQ Zones discrepancy from LOTW CQ zones.

### ISSUE THREAD

**Issue by n6paz** [ea4k/klog#462]
I noticed that my  WAZ "Awards" counts did not match the LOTW count.   After investigation I found that Klog CQ WAZ had a  discrepancy from LOTW CQ zones for zones: 2,3,4,18,29 and 31.   See ARRL LOTW CQ table attached. 

VE2GSO  LOTW reports zone 2,  Klog reports zone 5.
N7UVH  LOTW reports, zone 3, Klog reports zone 5.
W0AIH LOTW  reports, zone 4, Klog reports zone 5.
RA9YN LOTW reports, zone 18, Klog reports zone 17.
VK5DOC LOTW reports, zone 29, Klog reports, zone 30.
KH6LC LOTW reports, zone 31, Klog reports, zone 30.

![Screenshot 2022-06-06 040946](https://user-images.githubusercontent.com/92184426/172153211-d9f8897f-3562-403a-8dde-73a9e185efcc.png)

**Comment by ea4k** [comment]
Thanks for the report.
KLog gets the CQ info from cty-csv (https://www.country-files.com)
Just doing some tests (after updating KLog to latest country file) I can confirm:

KLog reporting wrong:
(these are as you say but unfortunately these calls are not in the country files.)
VE2GSO
N7UVH
VK5DOC

KLog reporting OK:
(please update your country files and check what KLog is reporting)
W0AIH
RA9YN
KH6LC

So, I will see if I can get the CQ information from any other place, maybe I can identify when KLog & LoTW differs and ask the user to select which CQ zone should be used...

Any suggestion?

Thanks again for the report!
