### ISSUE TITLE
KLOG thinks LM9L40Y is a invalid call sign. 

### ISSUE THREAD

**Issue by n6paz** [ea4k/klog#475]
KLOG thinks LM9L40Y is a invalid call sign, however it's real. 

https://qrz.com/db/LM9L40Y

![QSLCard](https://user-images.githubusercontent.com/92184426/179625707-abbabbc8-c8a8-4920-a5cb-e312f07e5efd.jpg)

73's de Oscar, N6PAZ

**Comment by ea4k** [comment]
This is the same as #316

**Comment by ea4k** [comment]
I close this issue and I will keep the #316 for this feature.
