### ISSUE TITLE
Upload to QRZ or Clublog

### ISSUE THREAD

**Issue by TuxedoHam** [ea4k/klog#502]
Hi All,

I have an issue uploading to QRZ and Clublog without marking all my log with "Queue all the QSOs to be uploaded", the way I have been getting around this in some way is to go through that and only upload the date range I wish to upload that has not been added to QRZ and Clublog.

I never had this with Devuan (Debain fork), I have recently moved this laptop back to Debian (testing) and the issue has started with 2.1.1, I have gone through the fresh install process and re imported my log etc, I had the issue with 2.2.1 from unstable.

**Comment by ea4k** [comment]
Can you please reword the issue? I am not able to understand the issue. 
Thank you.

**Comment by TuxedoHam** [comment]
I have an issue uploading new QSO's to QRZ and Clublog. I can't queue new QSO's (that haven't previously been uploaded) on their own. The only way I can is to queue all (including ones already uploaded), then filter that by date/time so that only the QSO's that weren't previously uploaded are queued.

This worked as expected in 2.1.1, but since switching from Devuan to Debian I'm using 2.2.1 which is showing this bug.
