### ISSUE TITLE
Apostrophe related error

### ISSUE THREAD

**Issue by TuxedoHam** [ea4k/klog#503]
Hi All,

I have just recreated this error and it took me little bit to work it out and cause of it, but I have noted recently when I have pulled data with "Check the current callsign in QRZ.com" and some the European with have an Apostrophe it the data and Klog can't same the QSO till that Apostrophe is taken out of the QSO data from QRZ, and the following error that is given below.

> An unexpected error ocurred!!
> 
> If the problem persists, please contact the developers([klog@groups.io](mailto:klog@groups.io))for analysis:
> 
> Error in function: void MainWindow::slotQRZReturnPressed()
> Native Error: 1
> Error text: near "VK5ZSH": syntax error
> Failed query: UPDATE log SET call = 'VK3KK', bandid = '27', modeid = '24', qso_date = '2022-10-02 08:17:15', rst_sent = '+12', rst_rcvd = '-11', lognumber = '1', cont = 'OC', name = 'Shaun', distance = '497', gridsquare = 'QF12', freq = '7.075', freq_rx = '7.075', band_rx = '27', qth = 'Miners Rest Victoria'', operator = 'VK5ZSH', station_callsign = 'VK5ZSH', my_gridsquare = 'PF95IH', my_rig = '', my_antenna = '', my_sota_ref = '', my_vucc_grids = '', comment = '', qslmsg = '', dxcc = '150', cqz = '30', ituz = '59', qsl_via = '', tx_pwr = '5', rx_pwr = '', sota_ref = '', age = '', vucc_grids = '', iota = 'OC-001', sat_name = '', sat_mode = '', prop_mode = '',clublog_qso_upload_status = 'N', eqsl_qsl_sent = 'N', eqsl_qsl_rcvd = 'N', lotw_qsl_sent = 'N', lotw_qsl_rcvd = 'N', qrzcom_qso_upload_status = 'N', qsl_sent = 'N', qsl_sent_via = 'B', qsl_rcvd = 'N', qsl_rcvd_via = 'B' WHERE id = '1738'
> 
> Recommendation:Periodically export your data to ADIF to prevent a potential data loss.

Cheers n 73
de VK5ZSH

**Comment by ea4k** [comment]
This seems to be a duplicate of #453 caused because KLog os not checking user input for SQL Injection commands.

This is being worked to be solved.
I will close this issue and ask you to add any additional input to #453.
