### ISSUE TITLE
Wrong call identified, wrongly

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#506]
RU4H is identified as wrong call in KLog 2.2.1

**Comment by barjac** [comment]
Confirmed here too.

**Comment by ea4k** [comment]
It is not a bug of KLog but of the cty.dat file and has been reported.
It seems that there are several Russian calls listed as prefixes in the file, a "=" before the call, like in "=RU4H" is missing.

https://www.country-files.com/cty-dat-format/
