### ISSUE TITLE
Specials Callsigns cannot be imported via ADIF because of Callsign Checks

### ISSUE THREAD

**Issue by oe3gwu** [ea4k/klog#517]
I try to migrate from Windows to Linux, and I saw KLog is nice, but has some weird behaviour. I worked stations like "BV100" that I cannot import.

Is there a way to disable all Callsign checking and just import the data? I have not found one.

https://www.qrz.com/db/BV100

**Comment by ea4k** [comment]
You can disable the call check in the Settings->Misc->Check non-valid calls

However there is some work on this topic to keep the checking enabled but allow exceptions but I have not an estimated time for this feature.
https://github.com/ea4k/klog/issues/316
