### ISSUE TITLE
Download of cty.csv failed with the following error code: TLS initialization failed

### ISSUE THREAD

**Issue by fgil** [ea4k/klog#564]
Download of cty.csv failed during installation on Windows 10 with "TLS initialization failed"

Also tried Tools > Update cty.csv after installation and got the same error.

Is there a way to manually install the cty.csv file?

OS Information:
Edition	Windows 10 Home
Version	22H2
OS build	19045.2788
Experience	Windows Feature Experience Pack 120.2212.4190.0

![Capture](https://user-images.githubusercontent.com/210206/231329446-7cf119e6-4b19-42c9-8e0f-c58f4a4fe097.PNG)

**Comment by ea4k** [comment]
Cty.dat can be downloaded from here:

https://www.country-files.com/big-cty/

You should copy the file in the klog folder  and click on update cty.dat

**Comment by fgil** [comment]
Pasting the file in the klog folder under the user folder (C:\Users\_username_\klog) worked. Pasting it in the installation folder (C:\Program Files (x86)\KLog) didn't.

Thanks

**Comment by ea4k** [comment]
I can't reproduce the message in windows 10, KLog-2.3.1
