### ISSUE TITLE
Can't manually enter a QSO.

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#575]
User Can't manually enter a QSO. Impossible to select a band (spin wheel inoperative) in manual mode. This seems broken in many ways which appear to change depending on the sequence of events preceding.

**Comment by ea4k** [comment]
Not only Manual Mode. After that, I reboot KLog and Bands are empty.
Entering two times to Setup, now is OK

**Comment by ea5wa** [comment]
Exactly, is not only in Manual Mode. Everytime I start KLog, Bands checklist is empty. After entering and quitting to Setup, Bands Checklist is complete according to Setup-Bands selection

**Comment by ea4k** [comment]
Closed by PR: https://github.com/ea4k/klog/pull/579
