### ISSUE TITLE
frequency display is rounded to 1kHz

### ISSUE THREAD

**Issue by barjac** [ea4k/klog#595]
In digital voice mode (FreeDV) it is common especially on 60m band to use e.g. 5366.5 kHz to place the signal in the centre of a licensed channel.
Could klog be extended to show MHz to 4 decimal places?

**Comment by ikbenkous** [comment]
See #622 and pull frequest #626

**Comment by ikbenkous** [comment]
@barjac @ea4k This issue can be closed since it's fixed by #626 (now merged).
