### ISSUE TITLE
QRZ uploads not queued for new QSOs. All are set to 'Do not upload'

### ISSUE THREAD

**Issue by barjac** [ea4k/klog#597]
This has been happening now for a long time and it is really tedious to have to manually edit every contact to 'Modified'.
Please can this be made a high priority for the next release?

**Comment by ea4k** [comment]
I don't understand the issue exactly.  Can you please explain again/further?

**Comment by barjac** [comment]
This is fixed in latest. :)

The QRZ.com field in the eQSL tab for new records was being set as "Do not upload" rather than "Modified". Nothing was appearing to upload to QRZ until all new records were manually changed to "Modified". :(
