### ISSUE TITLE
Enhancement: Dutch translation

### ISSUE THREAD

**Issue by ikbenkous** [ea4k/klog#633]
Should I just start hacking away and make a PR on this?
Or do I need to keep something in mind?
This might take me a couple days and dunno what the quality is gonna be.
Let's just say that Dutch isn't my strong suit. Haha

**Comment by ikbenkous** [comment]
I've decided to go for the formal "u" and "uw" to address the user instead of the lesser formal "je", "jij" and "jouw".
We don't know in what context klog is used. Being formal is just a bit more _stylish_ in my eyes.

Feedback appreciated.

**Comment by ea4k** [comment]
PR for translations of TS files are the best way to proceed. 
Thank you!
