### ISSUE TITLE
Satellite selection is not restored when editing a log entry.

### ISSUE THREAD

**Issue by n6paz** [ea4k/klog#655]
Klog version 2.3.2

When editing a logged QSO already saved with a satellite selection, the field is not populated with the saved satellite.

**Comment by ea4k** [comment]
Already fixed in 2.3.3, with but #648

KLog 2.3.3 will be released very soon.
You can find a preview here:
https://drive.google.com/drive/folders/1TupCFIC3_5sjryW-iBUazmHa0jUwekLM
