### ISSUE TITLE
After Editing a QSO, lotw_qsl_rcvd is emptied

### ISSUE THREAD

**Issue by ea5wa** [ea4k/klog#659]
After double-click in a QSO modify something (or not) and save changes, lotw_qsl_rcvd content for that QSO is emptied (there was a "N" but now is null in the DataBase). 

![image](https://github.com/ea4k/klog/assets/54686689/29a98cef-8226-4744-84ce-e6daf94f7c13)

In addition, lotw_qslrdate is not properly filled. Some QSOs with date of reception has an status "N"

![image](https://github.com/ea4k/klog/assets/54686689/7dd5ee30-920a-46d5-ba2f-60768ae3ab8d)

**Comment by ea4k** [comment]
Duplicated of #656
