### ISSUE TITLE
Several fields do not meet ADIF specification

### ISSUE THREAD

**Issue by ea5wa** [ea4k/klog#669]
- SWL is defined as boolean, but KLog is saving Y/N
- QSO_RANDOM is defined as boolean, but KLog is saving 0 in that field

There more fields saving "-1" that must contain a positive integer value.

**Comment by ea4k** [comment]
Freq and Distance also fail

![IMG_20240128_221647_462.jpg](https://github.com/ea4k/klog/assets/29511627/9ced10e3-fb43-4aa0-9802-5a05f8b33d56)

![IMG_20240128_221642_758.jpg](https://github.com/ea4k/klog/assets/29511627/9b36b6d9-e5d5-4eb2-93e4-eae56801fda6)

**Comment by ea4k** [comment]
This bug will manage only boolean fields:
FORCE_INIT
SILENT_KEY
SWL
QSO_RANDOM

QSO_COMPLETE is managed in #680
