### ISSUE TITLE
FO/x calls are not properly identified/stored

### ISSUE THREAD

**Issue by ea4k** [ea4k/klog#677]
![IMG_20240128_221432_781.jpg](https://github.com/ea4k/klog/assets/29511627/f5d4880b-acfb-429f-9f9f-ba2281139447)

![IMG_20240128_221412_152.jpg](https://github.com/ea4k/klog/assets/29511627/ae71950c-df69-4c05-8717-f64800950d6d)

![IMG_20240128_221304_478.jpg](https://github.com/ea4k/klog/assets/29511627/531ba6b5-8ab4-4561-ba2a-67a321e9b223)

**Comment by ea5wa** [comment]
getCQzFromPrefix function in dataproxy class is returning "-1" with TX5S (Clipperton Island) although is correctly defined in cty.dat and in prefixesofentity table

**Comment by ea5wa** [comment]
![image](https://github.com/ea4k/klog/assets/54686689/cbe977f4-7aa5-4ce9-9038-928d9116dd32)

**Comment by ea5wa** [comment]
ITU Zone is correctly saved but CQ Zone is failing

**Comment by ea4k** [comment]
Seems to identify the DXCC but fails to store that values properly 
![IMG_20240203_135659_371.jpg](https://github.com/ea4k/klog/assets/29511627/ef67d7ed-94d6-40ce-a646-e3d36ae842ab)

**Comment by ea5wa** [comment]
Solved using function world->getEntityCqz(dxcc) in mainwindow

**Comment by ea5wa** [comment]
![image](https://github.com/ea4k/klog/assets/54686689/8885e130-0248-411c-b089-13a53995a5d9)
