### ISSUE TITLE
Klog forgets my MODES settings or I do not understand this "feature".

### ISSUE THREAD

**Issue by betzburger** [ea4k/klog#685]
Hi,

I imported my logbook from LOTW and the import data was not correct. It mentioned MFSK instead of FT4.
In the settings under Modes FT4 was not checked only FT8.  So I did that but everytime when I come back this setting is unchecked again.
Is this a bug or a feature that I don't understand?

Peter

**Comment by ea4k** [comment]
Solved in 2.3.4
