### ISSUE TITLE
eQSL (LoTW) option not saved

### ISSUE THREAD

**Issue by KB2YSI** [ea4k/klog#686]
When you select LoTW it does not save the selection.

![image](https://github.com/ea4k/klog/assets/55863352/0f1c2156-f996-46da-b95b-613fea391431)

Save the QSO

![image](https://github.com/ea4k/klog/assets/55863352/d31d7777-66f6-4ebe-adec-b927df5d9a25)

**Comment by ea4k** [comment]
Solved in 2.3.4-RC4. Will be released soon in 2.3.4
